version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.18
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GDT9MbJUTFHpyJyeS2JxzgkpYTjnrU8v
    command: mongod --port ${MONGODB_PORT:-27017}
    ports:
      - 27017

  chatgptg:
    container_name: chatgptg
    command: python3 -m bot
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - AUTO_LANG=es
      - MONGODB_HOST=mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=GDT9MbJUTFHpyJyeS2JxzgkpYTjnrU8v
      - TELEGRAM_TOKEN=yourbottoken
      - USER_WHITELIST = 89727e9, mamador,   rrjrj,6077244180
      - DIALOG_TIMEOUT=7200
      - OUTPUT_IMAGES=4
      - TIMEOUT_ASK=True
      - FEATURE_TRANSCRIPTION=True
      - FEATURE_IMAGE_READ=True
      - FEATURE_IMAGE_GENERATION=True
      - GENERATED_IMAGE_EXPIRATION_MINUTES=5
      - FEATURE_BROWSING=True
      - FEATURE_DOCUMENT_READ=True
      - FEATURE_URL_READ=True
      - MAX_ITEMS_PER_PAGE=8
      - MAX_COLUMNS_PER_PAGE=2
      - AUDIO_MAX_MB=20
      - DOC_MAX_MB=2
      - URL_MAX_MB=1
      - PDF_PAGE_LIMIT=35
      - REQUEST_MAX_RETRIES=5
      - REQUEST_TIMEOUT=7
      - GPT4FREE_BING_U_COOKIE=LOOOOOOOOONGGGGGCOOOKIEEEEE882738319271$$$$
      - GPT4FREE_CHATGPT_SESSION_TOKEN=LOOOOOOOOONGGGGGCOOOKIEEEEE882738319271$$$$
#opcional    volumes:
#      - /ruta-fuera-del-docker/mi-configuracion:/config
