version: "3"

services:
  chatgpt-en-telegram:
    container_name: chatgpt-en-telegram
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - MONGODB_HOST=database.mongodb.net
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - TELEGRAM_TOKEN=yourbottoken
      - USER_WHITELIST = 89727e9, mamador,   rrjrj,6077244180
      - DIALOG_TIMEOUT=7200
      - OUTPUT_IMAGES=4
      - TIMEOUT_ASK=True
      - AUDIO_MAX_MB=20
      - DOC_MAX_MB=2
      - URL_MAX_MB=1
      - PDF_PAGE_LIMIT=50
      - GPT4FREE_BING_U_COOKIE=LOOOOOOOOONGGGGGCOOOKIEEEEE882738319271$$$$
      - GPT4FREE_CHATGPT_SESSION_TOKEN=LOOOOOOOOONGGGGGCOOOKIEEEEE882738319271$$$$
#opcional    volumes:
#      - /ruta-fuera-del-docker/mi-configuracion:/config
