available_api: ["openai", "you", "chatbase", "g4f"]
available_imagen: ["openai"]
available_transcript: ["openai"]
# debes declarar los api en el apartado de acá arriba
info:
  openai:
    name: OpenAI
    description: La API oficial.
    url: https://api.openai.com/v1
    key: sk-69420
    available_model: ["gpt-3.5-turbo", "gpt-4", "text-davinci-003"]

  you:
    name: You
    description: de You.com.
    url: youchat
    key: youkey
    available_model: ["gpt-3.5-turbo"]

  chatbase:
    name: ChatBase
    description: de ChatBase.co.
    url: youchat
    key: youkey
    available_model: ["gpt-3.5-turbo", "gpt-4"]

  g4f:
    name: GPT4Free
    description: API de APIs.
    url: http://127.0.0.1:1337
    key: ""
    available_model: ["g4f-you", "g4f-ails", "g4f-bing", "g4f-chatgpt", "g4f-phind", "g4f-yqcloud"]
  # otra_api:
  #   name: Otra
  #   description: Test.
  #   url: https://api.myapi.com/v1
  #   key: sk-69420
  #   available_model: ["gpt-3.5-turbo", "gpt-4", "text-davinci-003"]

  # "otra_api" debes añadirlo en available_api
  #(y available_imagen si esa api soporta generación de imágenes)
  # quedaría available_api: ["openai", "otra_api"]