available_max_tokens: ["token64", "token128", "token256", "token512", "token1024", "token2048", "token4096", "token8192"]


info:
  token64:
    name: 64
    description: muy ahorrativo

  token128:
    name: 128
    description: ahorrativo

  token256:
    name: 256
    description: normal
    
  token512:
    name: 512
    description: medio, suficiente
    
  token1024:
    name: 1024
    description: apto para textos largos
    
  token2048:
    name: 2048
    description: avaricia
    
  token4096:
    name: 4096
    description: a exprimir a los modelos.
    
  token8192:
    name: 8192
    description: da lo que se pueda!
    